name: Build and Deploy Front

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --file front/Dockerfile-deploy --tag cappu-f-d:${GITHUB_SHA::6} .
      - name: Deploy
        run: docker run -e NAME=github-actions-bot -e EMAIL=actions@github.com -e GITHUB_TOKEN=$GITHUB_TOKEN -e GITHUB_REPOSITORY=${GITHUB_REPOSITORY} cappu-f-d:${GITHUB_SHA::6}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
